services:
  web:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: django_app
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - web
    networks:
      - backend

volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  backend: